apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service
        image: yourdockerhub/video-backend
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: video-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
